### ISSUE TITLE
HW 1 Feedback

### ISSUE THREAD

**Issue by alexchaomander** [coolcalbeans/DAT_SF_12#1]
- May not have been clearly communicated through the instructions, but we wanted you to create an app token so that you could interact with the API. What you have works but using the app token will have allowed you to do data[0] and see results. 
- Use this url to access the API with a working token https://data.sfgov.org/resource/vw6y-z8j6.json?$$app_token=Iq3JEcmMzuOIvahirX7cR0GTI
- This will change a few of the column names, notably media_url. So you’d only need to drop ‘point’ 
- for the second part of number 2, you can just do a data[0]. Printing it like this may or may not be clearer to someone who wants to know the structure of the data
- Nice work using a different method than the solutions to generate the SQL database. Look at the solutions for how we did it. As long as it works :)
- For number 8, I think we were looking for Category not request_type, but this is just as informative as well
- All in all, good work. In general, query results were what we were expecting and hopefully you were able to get more familiar with pandas.

**Comment by coolcalbeans** [comment]
Thanks for the feedback, Alex....Just getting a hang of closing things in here :)
